### ISSUE TITLE
Where will we do the wiki?

### ISSUE THREAD

**Issue by vongohren** [din-ssi/wallet#5]
I dont mind trying github, but then I do believe that we need to go more collectivly on this.

Coda can always be a fallback when things is not up to standards, but as the current setup is, it is not optimal.

The only thing that a wiki here will be a problem for, is external people that is curious.

Why a seperate place for collecting information would be awesome

Mariuz from email: '
I like Discourse, but, for streamlining work here, I think we need four components:

* Code. Git is the only way to deal with it, and, issue tracker is the way to discuss code, make decisions, and report things. ß Github + Git
* Static documentation, like the onboarding Wiki page for new students, as I have suggested.  It is not to be “discussed”, but, it is to be “read” – in a form of manual, or static links. We could use something more structured, like coda.io for it, or a plain wiki, or like we do now, a Google Doc.
* Place to document structured discussions and to make decisions (discourse would fit great, but, so would Issue tracker on Github, I’ve used it almost like discourse – top level discussion issues + follow up comments.
* Chat for just chatting (Slack, Discord, e-mail (not great))
'

**Comment by gtl-hig** [comment]
How about we start with a public-facing Wiki on DIN-Foundation, for resources, on boarding new students, etc? Effectively migrating a bit what we have currently in the google doc.   We only use the din-ssi wiki for internal howto's and for things related to the working prototypes, but keeping everything else on the main public wiki already on the DIN-Foundation?  Perhaps @Arxics could start with the "on boarding" structure, because the way we would structure it is already bias - he has a fresh perspective.

**Comment by vongohren** [comment]
So the github wikis are thighly connected to repos, not organizations.
Which again gives a +1 to keeping a private team with private repos in DIN, if the plan is to move things back and forth anyway?

**Comment by Arxcis** [comment]
One "trick" to get a wiki coupled to an organization on github, instead of to a specific project, is to simply create a `wiki`-repo. Example: `github.com/din-foundation/wiki`.

**Comment by Arxcis** [comment]
Btw, just a week ago I read this blog post from mozilla describing how they plan to move to a model where all their wiki documents are hosted on github! See: https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/
![image](https://user-images.githubusercontent.com/3092618/98858339-bb229c00-2460-11eb-92f7-a96628d5aae4.png)

>With the new JAMStack approach, the writers are served separately from the readers. The writers manage the document content via a GitHub repository and pull request model, while the readers are served document pages more quickly and efficiently via pre-rendered document pages served from S3 via a CDN (which will have a much longer caching period). The document content from our GitHub repository will be rendered and deployed to S3 on a daily basis.

Of course at a much bigger scale, but nice to know what others are doing.

**Comment by vongohren** [comment]
THanks for that suggestion, and it sounds good. I dont mind doing wiki here!

Here are some nice tools used on the ssi and standarization community

https://identity.foundation/spec-up/
https://github.com/transmute-industries/respec-github-pages
https://github.com/w3c/spec-prod

Guess it just comes down to what organization we wokr under

**Comment by Arxcis** [comment]
Great :+1: From what I have read, identity.foundation sounds like it is very close to din-foundation, in terms of what it is working on. I don't know what transmute does. I guess w3c is the root foundation. So the question is, do we want to be siblings with identity.foundation or do we want to be children, in terms of "who we work under"? :smile:

**Comment by vongohren** [comment]
# Conclusion
To conclude, we do wiki on github and move it around as needed as suggested above.

# Information for rest of discussion
w3c is a standarization body for web.
Idenitity.foundation is a global main technical producing organization but also standarization body, working with w3c and all other organizations that produces important standards.
Transmute is a private company working for this, and doing consulting companies

din.foundation comes in to put this into a context of the Nordics. We are not building standards unless we find something really crucial along our journey. We do build components as a community, not as an organization, preferebly backed up by all the stuff available out there. And if you want to see how we do work you can check this: https://www.din.foundation/nyheter/how-do-we-relate-to-other-organizations

din.foundation is a organization facilitating the movement of SSI in the nordics. Because doing it in silos never work. So just gathering and informing and applying for reasearch projects and doing politics to get the thing moving.

Diwala is a member of DIN :D
